---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: ubuntu
  vars:
    ec2_region: us-east-1
    ec2_instance_type: t2.micro
    ec2_image: ami-c8580bdf
    ec2_keypair: bastion-key
    ec2_security_group: sg_ec2_public
    ec2_tag_Name: DynamicQA
    ec2_subnet_ids: subnet-04d43938
    ec2_tag_Type: webserver
    ec2_tag_Environment: DynamicQA
    ec2_volume_size: 8

  tasks:
    - name: finding all running instances
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ ec2_tag_Name }}"
        region: "{{ ec2_region }}"
      register: all_ec2

    - debug: var=item.public_ip
      with_items: "{{ all_ec2.instances }}"

    - name: Terminate all existing Ec2 instances
      local_action:
        module: ec2
        region: "{{ ec2_region }}"
        # instance_tags:
        #     Name: "{{ ec2_tag_Name }}"
        state: absent
        instance_ids: '{{ item.public_ip }}'
      ignore_errors: true
      with_items: "{{ all_ec2.instances }}"

    - name: launch ec2 instance for QA
      local_action:
        module: ec2
        key_name: "{{ ec2_keypair }}"
        group: "{{ ec2_security_group }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        vpc_subnet_id: "{{ ec2_subnet_ids }}"
        region: "{{ ec2_region }}"
        instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
        assign_public_ip: yes
        wait: true
        count: 1
      register: ec2

    - debug: var=item
      with_items: "{{ ec2.instances }}"

    - add_host:
        name: "{{ item.public_ip }}"
        groups: dynamically_created_hosts
      with_items: "{{ ec2.instances }}"

    - name: Wait for the instances to boot by checking the ssh port
      wait_for: host="{{ item.public_ip }}" port=22 delay=60 timeout=320 state=started
      with_items: "{{ ec2.instances }}"

# - hosts: dynamically_created_hosts
#   tasks:
#   - debug: msg="do things on target host here"
