---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: ubuntu
  vars:
    region: us-east-1
    instance_type: t2.micro
    image: ami-c8580bdf
    ssh_key: bastion-key
    sg_group: sg_ec2_public
    tag_name: QA

  tasks:
    - name: launch ec2 instance for QA
      local_action:
        module: ec2
        region: "{{ region }}"
        key_name: "{{ ssh_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        wait_timeout: 500
        vpc_subnet_id: subnet-04d43938
        group: "{{ sg_group }}"
        instance_tags:
          Name: "{{ tag_name}}"
      register: ec2_create

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2_create.instances

    - add_host:
        name: "{{ item.public_dns_name }}"
        groups: dynamically_created_hosts
        with_items: ec2_create.instances

- hosts: dynamically_created_hosts
  tasks:
  - debug: msg="do things on target host here"
