---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: yes
  remote_user: ubuntu
  vars:
    region: us-east-1
    instance_type: t2.micro
    image: ami-c8580bdf
    ssh_key: bastion-key
    sg_group: sg_ec2_public
    tag_name: QA

  tasks:
    - name: launch ec2 instance for QA
      local_action:
        module: ec2
        region: "{{ region }}"
        key_name: "{{ ssh_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        wait_timeout: 500
        group: "{{ sg_group }}"
        instance_tags:
          Name: "{{ tag_name}}"
